### ISSUE TITLE
Add jinja2 support for config file(and maybe for user scripts)

### ISSUE THREAD

**Issue by madeline-scyphers** [madeline-scyphers/boa#128]
Adding jinja2 support in the config files would allow a lot more dynamic abilities for configuration and scripts. Jinja2 is a pseudo code for substitution in various static files. Examples of what you could do:

instead of having to do something like this if you have 8 parameters all ranging form (0,1)
```yaml
parameters:
    x0:
        type: range
        bounds: [0, 1]
        value_type: float
    x1:
        type: range
        bounds: [0, 1]
        value_type: float
    x2:
        type: range
        bounds: [0, 1]
        value_type: float
    x3:
        type: range
        bounds: [0, 1]
        value_type: float
    x4:
        type: range
        bounds: [0, 1]
        value_type: float
    x5:
        type: range
        bounds: [0, 1]
        value_type: float
    x6:
        type: range
        bounds: [0, 1]
        value_type: float
    x7:
        type: range
        bounds: [0, 1]
        value_type: float
```

you could do:
```yaml
parameters:
    {% for i in range(8) %}
    x{{ i }}:
        type: range
        bounds: [0, 1]
        value_type: float
    {% endfor %}
```

Other potential things you could do in a user script wrapper script, instead of having to do `trial_dir` as a command line argument to scripts, users could instead do this, which has advantages in situations where scripts (or executables) are written in ways to not take command like arguments. Also this probably lower the barrier of entry.

current way
```R
args <- commandArgs(trailingOnly=TRUE)
trial_dir <- args[length(args)]

param_path <- file.path(trial_dir, "parameters.json")
data <- read_json(path=param_path)
```

potential new way
```R
param_path <- {{ param_path }}
data <- read_json(path=param_path)
```

You could have a potential large amount of variables available to the user that they could conveniently access this way, making their scripts easier.

 It introduces problems if `{{`, `}}`, `{%`, or `%}` are needed in a user script (unlikely since jinj2 choose these as unused and unlikely symbols), but this could be mitigated by allowing these symbols to be changed in the config if needed (since jinja2 does allow this to e changed)
